"""empty message

Revision ID: dcf857e540e8
Revises: 822a3302a39e
Create Date: 2021-05-29 18:45:56.791512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf857e540e8'
down_revision = '822a3302a39e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'reviews', 'users', ['users_id'], ['id'])
    op.create_foreign_key(None, 'reviews', 'problems', ['problems_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    # ### end Alembic commands ###
