"""empty message

Revision ID: efe2e31e0cf6
Revises: c46e585b27d7
Create Date: 2021-06-01 17:09:39.667106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe2e31e0cf6'
down_revision = 'c46e585b27d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('example', sa.String(), nullable=True))
    op.alter_column('problems', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('problems', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('problems', 'example')
    # ### end Alembic commands ###
