"""empty message

Revision ID: c46e585b27d7
Revises: 6639b3853fcf
Create Date: 2021-05-31 10:22:18.042452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c46e585b27d7'
down_revision = '6639b3853fcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('language', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'language')
    # ### end Alembic commands ###
