"""empty message

Revision ID: 833314dc8d1f
Revises: efe2e31e0cf6
Create Date: 2021-06-02 21:34:31.689525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833314dc8d1f'
down_revision = 'efe2e31e0cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fname', sa.String(), nullable=False))
    op.add_column('users', sa.Column('lname', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lname')
    op.drop_column('users', 'fname')
    # ### end Alembic commands ###
